name: uniko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logger: ^2.0.2+1
  flutter_html: ^3.0.0-beta.2
  local_auth: ^2.1.8
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  pie_chart: ^5.4.0
  animations: ^2.0.8
  fl_chart: ^0.70.0
  tab_indicator_styler: ^2.0.0
  marquee: ^2.2.3
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  flutter_slidable: ^3.0.1
  lottie: ^3.0.0
  form_builder_validators: ^11.1.1
  flutter_form_builder: ^9.2.1
  salomon_bottom_bar: ^3.3.2
  expandable: ^5.0.1
  flutter_localizations:
    sdk: flutter
  animated_custom_dropdown: ^2.0.0
  tab_container: ^2.0.0
  calendar_date_picker2: ^0.5.3
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  flutter_time_picker_spinner: ^2.0.0
  dio: ^5.4.0 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/avatars/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true