// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIRMUWBVxBiyOuG-8EUGcMlvoONtm7uY',
    appId: '1:245986889211:web:ab5dc50bc4440263698f5e',
    messagingSenderId: '245986889211',
    projectId: 'uniko-479fd',
    authDomain: 'uniko-479fd.firebaseapp.com',
    storageBucket: 'uniko-479fd.firebasestorage.app',
    measurementId: 'G-NSDZECKEN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRUvJlsazvxpUj38bUAepJNm7rEFvUEA',
    appId: '1:245986889211:android:ed53470c13c5da4c698f5e',
    messagingSenderId: '245986889211',
    projectId: 'uniko-479fd',
    storageBucket: 'uniko-479fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRf4vZO8yw9bwIdlGa_NK7LjZfG9luVM',
    appId: '1:245986889211:ios:41d853b6aff60dfa698f5e',
    messagingSenderId: '245986889211',
    projectId: 'uniko-479fd',
    storageBucket: 'uniko-479fd.firebasestorage.app',
    iosBundleId: 'com.example.uniko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLRf4vZO8yw9bwIdlGa_NK7LjZfG9luVM',
    appId: '1:245986889211:ios:41d853b6aff60dfa698f5e',
    messagingSenderId: '245986889211',
    projectId: 'uniko-479fd',
    storageBucket: 'uniko-479fd.firebasestorage.app',
    iosBundleId: 'com.example.uniko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZIRMUWBVxBiyOuG-8EUGcMlvoONtm7uY',
    appId: '1:245986889211:web:2623721afad6cd23698f5e',
    messagingSenderId: '245986889211',
    projectId: 'uniko-479fd',
    authDomain: 'uniko-479fd.firebaseapp.com',
    storageBucket: 'uniko-479fd.firebasestorage.app',
    measurementId: 'G-J5YBTCWJ5D',
  );
}
